Replace hard tab with four spaces

diff --git a/bin/freight-cache b/bin/freight-cache
--- a/bin/freight-cache
+++ b/bin/freight-cache
@@ -16,45 +16,45 @@
 set -e
 
 usage() {
-	grep "^#/" "$0" | cut -c"4-" >&2
-	exit "$1"
+    grep "^#/" "$0" | cut -c"4-" >&2
+    exit "$1"
 }
 while [ "$#" -gt 0 ]
 do
-	case "$1" in
-		-k|--keep) KEEP=1 shift;;
-		-g|--gpg)
-			if [ -z "$GPG" ]; then
-				GPG=$2
-			else
-				GPG="$GPG $2"
-			fi
-			shift 2;;
-		-g*)
-			if [ -z "$GPG" ]; then
-				GPG=$(echo "$1" | cut -c"3-")
-			else
-				GPG="$GPG $(echo "$1" | cut -c"3-")"
-			fi
-			shift;;
-		--gpg=*)
-			if [ -z "$GPG" ]; then
-				GPG=$(echo "$1" | cut -c"7-")
-			else
-				GPG="$GPG $(echo "$1" | cut -c"7-")"
-			fi
-			shift;;
-		-p|--passphrase-file) GPG_PASSPHRASE_FILE="$2" shift 2;;
-		-p*) GPG_PASSPHRASE_FILE="$(echo "$1" | cut -c"3-")" shift;;
-		--passphrase-file=*) GPG_PASSPHRASE_FILE="$(echo "$1" | cut -c"19-")" shift;;
-		-c|--conf) CONF="$2" shift 2;;
-		-c*) CONF="$(echo "$1" | cut -c"3-")" shift;;
-		--conf=*) CONF="$(echo "$1" | cut -c"8-")" shift;;
-		-v|--verbose) VERBOSE=1 shift;;
-		-h|--help) usage 0;;
-		-*) echo "# [freight] unknown switch: $1" >&2;;
-		*) break;;
-	esac
+    case "$1" in
+        -k|--keep) KEEP=1 shift;;
+        -g|--gpg)
+            if [ -z "$GPG" ]; then
+                GPG=$2
+            else
+                GPG="$GPG $2"
+            fi
+            shift 2;;
+        -g*)
+            if [ -z "$GPG" ]; then
+                GPG=$(echo "$1" | cut -c"3-")
+            else
+                GPG="$GPG $(echo "$1" | cut -c"3-")"
+            fi
+            shift;;
+        --gpg=*)
+            if [ -z "$GPG" ]; then
+                GPG=$(echo "$1" | cut -c"7-")
+            else
+                GPG="$GPG $(echo "$1" | cut -c"7-")"
+            fi
+            shift;;
+        -p|--passphrase-file) GPG_PASSPHRASE_FILE="$2" shift 2;;
+        -p*) GPG_PASSPHRASE_FILE="$(echo "$1" | cut -c"3-")" shift;;
+        --passphrase-file=*) GPG_PASSPHRASE_FILE="$(echo "$1" | cut -c"19-")" shift;;
+        -c|--conf) CONF="$2" shift 2;;
+        -c*) CONF="$(echo "$1" | cut -c"3-")" shift;;
+        --conf=*) CONF="$(echo "$1" | cut -c"8-")" shift;;
+        -v|--verbose) VERBOSE=1 shift;;
+        -h|--help) usage 0;;
+        -*) echo "# [freight] unknown switch: $1" >&2;;
+        *) break;;
+    esac
 done
 
 LIB="$(cd "$(dirname "$(dirname "$0")")/lib/freight" && pwd)"
@@ -79,40 +79,40 @@ cd "$VARLIB"
 # Rebuild each distro serially.
 if [ -z "$*" ]
 then
-	DIRS="$(
-		find "$VARLIB" -mindepth 2 -maxdepth 2 -type d -printf "%P\n" |
-		grep -v "^\\." |
-		tr "\n" " "
-	)"
+    DIRS="$(
+        find "$VARLIB" -mindepth 2 -maxdepth 2 -type d -printf "%P\n" |
+        grep -v "^\\." |
+        tr "\n" " "
+    )"
 else
-	DIRS=$*
+    DIRS=$*
 fi
 for DIR in $DIRS
 do
 
-	# Parse the manager and distro out of the Freight library path.
-	DIR="$(readlink -f "$DIR")"
-	DIR="${DIR##"$VARLIB/"}"
-	MANAGER="$(dirname "$DIR")"
-	DIST="$(basename "$DIR")"
+    # Parse the manager and distro out of the Freight library path.
+    DIR="$(readlink -f "$DIR")"
+    DIR="${DIR##"$VARLIB/"}"
+    MANAGER="$(dirname "$DIR")"
+    DIST="$(basename "$DIR")"
 
-	# Should we follow symbolic links when finding components to cache?
-	[ "$SYMLINKS" = "on" ] && FIND_L="-L" || FIND_L=""
+    # Should we follow symbolic links when finding components to cache?
+    [ "$SYMLINKS" = "on" ] && FIND_L="-L" || FIND_L=""
 
-	# From here the process is customized on a per-manager basis.  The
-	# sorted list of package filenames comes on `stdin` and the name of
-	# the distro is the only argument.  From there, each manager can do
-	# whatever it wants.
-	. "$LIB/$MANAGER.sh"
-	SORT="$(sort -V <"/dev/null" 2>"/dev/null" && echo "sort -V" || echo "sort")"
-	find $FIND_L "$DIR" -type "f" -printf "%P\n" 2>"/dev/null" |
-	eval "$SORT" |
-	eval "${MANAGER}_cache" "$DIST"
+    # From here the process is customized on a per-manager basis.  The
+    # sorted list of package filenames comes on `stdin` and the name of
+    # the distro is the only argument.  From there, each manager can do
+    # whatever it wants.
+    . "$LIB/$MANAGER.sh"
+    SORT="$(sort -V <"/dev/null" 2>"/dev/null" && echo "sort -V" || echo "sort")"
+    find $FIND_L "$DIR" -type "f" -printf "%P\n" 2>"/dev/null" |
+    eval "$SORT" |
+    eval "${MANAGER}_cache" "$DIST"
 
-	# Clean up old packages as dictated by the manager.
-	if [ -z "$KEEP" ]; then
-		eval "${MANAGER}_clean"
-	fi
+    # Clean up old packages as dictated by the manager.
+    if [ -z "$KEEP" ]; then
+        eval "${MANAGER}_clean"
+    fi
 
 done
 
