Clean up the pool.
The -k option has moved to freight-cache which now uses a .refs directory to remove old versions when their link count falls to one and -k is not given.

diff --git a/bin/freight-cache b/bin/freight-cache
--- a/bin/freight-cache
+++ b/bin/freight-cache
@@ -8,8 +8,9 @@ set -e
 
 # Combined usage message and help screen.
 usage() {
-	echo "Usage: $(basename $0) [-g <email>] [-c <conf>] [-V] [-v] [-h] <manager>/<distro>..." >&2
+	echo "Usage: $(basename $0) [-k] [-g <email>] [-c <conf>] [-V] [-v] [-h] <manager>/<distro>..." >&2
 	[ -n "$1" ] && {
+		echo "  -k, --keep                keep old versions of packages" >&2
 		echo "  -g <email>, --gpg=<email> GPG key to use" >&2
 		echo "  -c <conf>, --conf=<conf>  config file to parse" >&2
 		echo "  -V, --verbose             verbose mode" >&2
@@ -22,6 +23,10 @@ usage() {
 while [ "$#" -gt 0 ]
 do
 	case "$1" in
+		-k|--keep)
+			KEEP=1
+			shift
+			;;
 		-g|--gpg)
 			GPG="$2"
 			shift 2
@@ -86,10 +91,9 @@ do
 	# the distro is the only argument.  From there, each manager can do
 	# whatever it wants.
 	. "$MANAGER.sh"
-	ls "$DIR" 2>/dev/null | sort -V | eval $MANAGER $DIST
+	ls "$DIR" 2>/dev/null | sort -V | eval ${MANAGER}_cache $DIST
+
+	# Clean up old packages as dictated by the manager.
+	[ -z "$KEEP" ] && eval ${MANAGER}_clean
 
 done
-
-# This isn't strictly necessary but it's a nice habit to leave everything
-# as it was found.
-cd - >/dev/null
